# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d701cadef4ec8914478119c68da73995"
name = "test-bul-app"
handle = "test-bul-app"
application_url = "https://americas-refused-warner-pray.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "emre-development-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://americas-refused-warner-pray.trycloudflare.com/auth/callback",
  "https://americas-refused-warner-pray.trycloudflare.com/auth/shopify/callback",
  "https://americas-refused-warner-pray.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
